# Generated by Django 4.2.4 on 2023-08-16 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'uav_categories',
            },
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('is_rental', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='uavs', to='uavs.uavcategory')),
            ],
            options={
                'db_table': 'uavs',
            },
        ),
        migrations.CreateModel(
            name='RentedUAV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_uavs', to='uavs.uav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_uavs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rented_uavs',
            },
        ),
    ]
