# Generated by Django 4.2.4 on 2023-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uavs', '0002_alter_uavcategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renteduav',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uav',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uavcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='renteduav',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='renteduav',
            name='start_date',
            field=models.DateField(),
        ),
    ]
